/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_alacrittyterminal_free: (a: number, b: number) => void;
export const alacrittyterminal_cell_height: (a: number) => number;
export const alacrittyterminal_cell_width: (a: number) => number;
export const alacrittyterminal_cols: (a: number) => number;
export const alacrittyterminal_connect: (a: number, b: number, c: number) => [number, number];
export const alacrittyterminal_disconnect: (a: number) => void;
export const alacrittyterminal_dispose: (a: number) => void;
export const alacrittyterminal_feed: (a: number, b: number, c: number) => void;
export const alacrittyterminal_frame_seq: (a: number) => number;
export const alacrittyterminal_keyboard_mode_bits: (a: number) => number;
export const alacrittyterminal_last_parse_ms: (a: number) => number;
export const alacrittyterminal_last_render_ms: (a: number) => number;
export const alacrittyterminal_mouse_reporting_active: (a: number) => number;
export const alacrittyterminal_new: (a: any) => [number, number, number];
export const alacrittyterminal_paste: (a: number, b: number, c: number) => void;
export const alacrittyterminal_pending_bytes: (a: number) => number;
export const alacrittyterminal_pending_chunks: (a: number) => number;
export const alacrittyterminal_renderer_backend: (a: number) => [number, number];
export const alacrittyterminal_report_mouse: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const alacrittyterminal_resize: (a: number, b: number, c: number) => void;
export const alacrittyterminal_rows: (a: number) => number;
export const alacrittyterminal_scroll: (a: number, b: number) => void;
export const alacrittyterminal_scroll_to_bottom: (a: number) => void;
export const alacrittyterminal_selection_clear: (a: number) => void;
export const alacrittyterminal_selection_line: (a: number, b: number, c: number) => void;
export const alacrittyterminal_selection_start: (a: number, b: number, c: number, d: number) => void;
export const alacrittyterminal_selection_text: (a: number) => [number, number];
export const alacrittyterminal_selection_update: (a: number, b: number, c: number, d: number) => void;
export const alacrittyterminal_selection_word: (a: number, b: number, c: number) => void;
export const alacrittyterminal_set_focused: (a: number, b: number) => void;
export const alacrittyterminal_set_font_family: (a: number, b: number, c: number) => void;
export const alacrittyterminal_set_font_size: (a: number, b: number) => void;
export const alacrittyterminal_set_line_height_multiplier: (a: number, b: number) => void;
export const alacrittyterminal_set_palette: (a: number, b: any) => [number, number];
export const alacrittyterminal_sync_canvas_size: (a: number) => void;
export const alacrittyterminal_write: (a: number, b: number, c: number) => void;
export const alacrittyterminal_ws_ready_state: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h5baad699b3dcff72: (a: number, b: number) => void;
export const closure129_externref_shim: (a: number, b: number, c: any) => void;
export const __wbindgen_start: () => void;
